apiVersion: kubeadm.k8s.io/v1beta3
caCertPath: /etc/kubernetes/pki/ca.crt
discovery:
  bootstrapToken:
    apiServerEndpoint: 10.240.0.11:6443
    token: abc123.def456ghi7sad211
    unsafeSkipCAVerification: true
  timeout: 5m0s
  tlsBootstrapToken: abc123.def456ghi7sad211
kind: JoinConfiguration
nodeRegistration:
  criSocket: unix:///var/run/containerd/containerd.sock
  imagePullPolicy: IfNotPresent
  kubeletExtraArgs:
    cloud-provider: gce
  taints: []